[package]
name = "bcsv"
version = "0.1.0"
authors = ["Hexilee <hexileee@gmail.com>", "YangKeao <keao.yang@yahoo.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
base_core_socialist_values = {path="../base_core_socialist_values", version="0.1"}
