[package]
name = "base_core_socialist_values"
version = "0.1.0"
authors = ["Hexilee <hexileee@gmail.com>", "YangKeao keao.yang@yahoo.com"]
edition = "2018"
description = "Encode and decode with BCSV (base core socialist values)"
license = "MIT"

[dependencies]
lazy_static = "1.3.0"
